# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTgzZGUxZTVhY2QxMTBhZmE3Y2RiNmE0NzlmZjU5YmNhYTk5YjNmOTgzMTU4YjQzOWFlOWZjODY2M2M0ZmYzMzJkZjE0NWU2MDA0ZjVkMTE3YjBjNTkxNjExZDJhZTU3NjRhMDExNmZjNjdiNjVjZTY5N2RmOGVmNzFkNzUyYzE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
